CREATE TABLE IF NOT EXISTS users(id SERIAL PRIMARY KEY, discord_id BIGINT UNIQUE, points BIGINT DEFAULT 0);
CREATE TABLE IF NOT EXISTS point_transactions(id SERIAL PRIMARY KEY,user_id BIGINT,amount INT,source TEXT,reason TEXT);
CREATE TABLE IF NOT EXISTS products(id SERIAL PRIMARY KEY,name TEXT,price INT,type TEXT,status BOOLEAN DEFAULT TRUE);
CREATE TABLE IF NOT EXISTS orders(id SERIAL PRIMARY KEY,user_id BIGINT,product_id INT,status TEXT);
